// This file ensures the manifest is correctly loaded
// The content is generated by oclif manifest command
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const manifestPath = path.join(__dirname, 'oclif.manifest.json');

// Export the manifest content
export default JSON.parse(fs.readFileSync(manifestPath, 'utf8')); 